#%RAML 1.0 NamedExample
inputexample:
  {
            accountno: "1234567890",
            atmpin: "0000" ,
            contact: 7057899330,
            depositAmount: 0,
            ifscCode: sbi444444,
            mailId: "abc@gmail.com"
          }